# Workspace that is used for this operation. Most of time, this is done on local.
workspace: release
# release version that is used to generate changelog. This need to be changed every time
version: 1.5.8
# github organization as the token is bound to the org in changelog generator. This
# means that you can only release multiple repositories within the same org each time.
organization: networknt
# clone and switch to develop branch / checkout and pull from develop branch
checkout:
  branch: develop
  repository:
  - git@github.com:networknt/light-4j.git
  - git@github.com:networknt/openapi-parser.git
  - git@github.com:networknt/light-rest-4j.git
  - git@github.com:networknt/light-graphql-4j.git
  - git@github.com:networknt/light-hybrid-4j.git
  - git@github.com:networknt/light-codegen.git
  - git@github.com:networknt/light-eventuate-4j.git
  - git@github.com:networknt/light-tram-4j.git
  - git@github.com:networknt/light-saga-4j.git
  - git@github.com:networknt/light-session-4j.git
  - git@github.com:networknt/light-proxy.git
  - git@github.com:networknt/light-oauth2.git
  - git@github.com:networknt/light-example-4j.git
  - git@github.com:networknt/light-docker.git
# merge develop to master, check in master and release master
release:
  - light-4j
  - openapi-parser
  - light-rest-4j
  - light-graphql-4j
  - light-hybrid-4j
#  - light-codegen
  - light-eventuate-4j
  - light-tram-4j
  - light-saga-4j
  - light-session-4j
#  - light-proxy
#  - light-oauth2
