# Singleton service factory configuration/IoC injection
singletons:
# Executor to CommandExecutor binding
- com.networknt.bot.core.Executor:
  - com.networknt.bot.core.CommandExecutor
- com.networknt.bot.core.Command:
  - com.networknt.bot.develop.DevelopBuildTask
  - com.networknt.bot.version.VersionCommand
  - com.networknt.bot.release.ReleaseMavenTask
  - com.networknt.bot.dockerhub.DockerhubCommand
  - com.networknt.bot.upgrade.UpgradeCommand
  - com.networknt.bot.regex.replace.RegexReplaceTask
