# Singleton service factory configuration/IoC injection
singletons:
# Executor to CommandExecutor binding
- com.networknt.bot.core.Executor:
  - com.networknt.bot.core.CommandExecutor
- com.networknt.bot.core.Command:
  - com.networknt.bot.develop.DevelopCommand
  - com.networknt.bot.version.VersionCommand
  - com.networknt.bot.release.ReleaseCommand
  - com.networknt.bot.dockerhub.DockerhubCommand
