# Workspace that is used for this operation. Most of time, this is done on local.
workspace: upgrade
# old existing version that need to be upgraded
old_version: 1.5.5
# new upgraded version. These two versions need to be updated every time to run this command
new_version: 1.5.6
# clone and switch to develop branch / checkout and pull from develop branch
checkout:
  branch: develop
  repository:
  - git@github.com:networknt/light-example-4j.git
# regex replacement for dependencies
version:
  light-example-4j/rest/swagger/petstore:
  - path: pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  light-example-4j/rest/openapi/petstore:
  - path: pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: pom.xml
    match: <version.openapi-parser>\d*\.\d*\.\d*</version.openapi-parser>
  light-example-4j/rest/swagger/proxy-backend:
  - path: pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  light-example-4j/rest/openapi/proxy-backend:
  - path: pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: pom.xml
    match: <version.openapi-parser>\d*\.\d*\.\d*</version.openapi-parser>
  light-example-4j/rest/openapi/cors:
  - path: pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: pom.xml
    match: <version.openapi-parser>\d*\.\d*\.\d*</version.openapi-parser>
  light-example-4j/rest/swagger/ms_chain/api_d/generated:
  - path: pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  light-example-4j/rest/swagger/ms_chain/api_c/generated:
  - path: pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  light-example-4j/rest/swagger/ms_chain/api_b/generated:
  - path: pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  light-example-4j/rest/swagger/ms_chain/api_a/generated:
  - path: pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  light-example-4j/rest/swagger/ms_chain/api_d/httpchain:
  - path: pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  light-example-4j/rest/swagger/ms_chain/api_c/httpchain:
  - path: pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  light-example-4j/rest/swagger/ms_chain/api_b/httpchain:
  - path: pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  light-example-4j/rest/swagger/ms_chain/api_a/httpchain:
  - path: pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  light-example-4j/rest/swagger/ms_chain/api_d/httpschain:
  - path: pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  light-example-4j/rest/swagger/ms_chain/api_c/httpschain:
  - path: pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  light-example-4j/rest/swagger/ms_chain/api_b/httpschain:
  - path: pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  light-example-4j/rest/swagger/ms_chain/api_a/httpschain:
  - path: pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  light-example-4j/rest/swagger/ms_chain/api_d/security:
  - path: pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  light-example-4j/rest/swagger/ms_chain/api_c/security:
  - path: pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  light-example-4j/rest/swagger/ms_chain/api_b/security:
  - path: pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  light-example-4j/rest/swagger/ms_chain/api_a/security:
  - path: pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  light-example-4j/rest/swagger/ms_chain/api_d/metrics:
  - path: pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  light-example-4j/rest/swagger/ms_chain/api_c/metrics:
  - path: pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  light-example-4j/rest/swagger/ms_chain/api_b/metrics:
  - path: pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  light-example-4j/rest/swagger/ms_chain/api_a/metrics:
  - path: pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  # tram examples
  # light-tram-todolist single-module
  light-example-4j/tram/light-tram-todolist/single-module:
  - path: pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  # light-tram-todolist multi-module
  light-example-4j/tram/light-tram-todolist/multi-module:
  - path: pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
# upgrade other files between the two versions. like config files etc.
# this command will only work on the repo like light-example-4j for built services.
upgrade:
