# Workspace that is used for this operation. Most of time, this is done on local.
workspace: version
# old existing version that need to be upgraded
old_version: 1.5.8
# new upgraded version. These two versions need to be updated every time to run this command
new_version: 1.5.9
# clone and switch to develop branch / checkout and pull from develop branch
checkout:
  branch: develop
  repository:
  - git@github.com:networknt/light-4j.git
  - git@github.com:networknt/openapi-parser.git
  - git@github.com:networknt/light-rest-4j.git
  - git@github.com:networknt/light-graphql-4j.git
  - git@github.com:networknt/light-hybrid-4j.git
  - git@github.com:networknt/light-codegen.git
  - git@github.com:networknt/light-eventuate-4j.git
  - git@github.com:networknt/light-tram-4j.git
  - git@github.com:networknt/light-saga-4j.git
  - git@github.com:networknt/light-session-4j.git
  - git@github.com:networknt/light-proxy.git
  - git@github.com:networknt/light-oauth2.git
  - git@github.com:networknt/light-example-4j.git
  - git@github.com:networknt/light-docker.git
# run mvn versions:set command in the following folders.
maven:
  - light-4j
  - openapi-parser
  - light-rest-4j
  - light-graphql-4j
  - light-hybrid-4j
  - light-codegen
  - light-eventuate-4j
  - light-tram-4j
  - light-saga-4j
  - light-session-4j
  - light-proxy
  - light-oauth2
# regex replacement for dependencies
version:
  openapi-parser:
  - path: pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  light-rest-4j:
  - path: pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: pom.xml
    match: <version.openapi-parser>\d*\.\d*\.\d*</version.openapi-parser>
  light-graphql-4j:
  - path: pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  light-hybrid-4j:
  - path: pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  light-codegen:
  - path: pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: pom.xml
    match: <version.openapi-parser>\d*\.\d*\.\d*</version.openapi-parser>
  - path: light-graphql-4j/src/main/resources/templates/graphql/pom.xml.rocker.raw
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: light-hybrid-4j/src/main/resources/templates/hybrid/server/pom.xml.rocker.raw
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: light-hybrid-4j/src/main/resources/templates/hybrid/service/pom.xml.rocker.raw
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: light-rest-4j/src/main/resources/templates/rest/openapi/pom.xml.rocker.raw
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: light-rest-4j/src/main/resources/templates/rest/openapi/pom.xml.rocker.raw
    match: <version.openapi-parser>\d*\.\d*\.\d*</version.openapi-parser>
  - path: light-rest-4j/src/main/resources/templates/rest/swagger/pom.xml.rocker.raw
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  light-eventuate-4j:
  - path: pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  light-tram-4j:
  - path: pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  light-saga-4j:
  - path: pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  light-session-4j:
  - path: pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  light-proxy:
  - path: pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: pom.xml
    match: <version.openapi-parser>\d*\.\d*\.\d*</version.openapi-parser>
  light-oauth2:
  - path: pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  light-example-4j:
  # eventuate account management
  - path: eventuate/account-management/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  # discovery api_a
  - path: discovery/api_a/consul/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: discovery/api_a/consuldocker/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: discovery/api_a/dynamic/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: discovery/api_a/generated/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: discovery/api_a/multiple/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: discovery/api_a/static/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: discovery/api_a/tag/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: discovery/api_a/token/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  # discovery api_b
  - path: discovery/api_b/consul/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: discovery/api_b/consuldocker/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: discovery/api_b/dynamic/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: discovery/api_b/generated/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: discovery/api_b/multiple/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: discovery/api_b/static/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: discovery/api_b/tag/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: discovery/api_b/token/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  # discovery api_c
  - path: discovery/api_c/consul/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: discovery/api_c/consuldocker/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: discovery/api_c/dynamic/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: discovery/api_c/generated/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: discovery/api_c/multiple/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: discovery/api_c/static/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: discovery/api_c/tag/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: discovery/api_c/token/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  # discovery api_d
  - path: discovery/api_d/consul/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: discovery/api_d/consuldocker/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: discovery/api_d/dynamic/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: discovery/api_d/generated/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: discovery/api_d/multiple/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: discovery/api_d/static/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: discovery/api_d/tag/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: discovery/api_d/token/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  # graphql subscription
  - path: graphql/subscription/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  # graphql helloworld
  - path: graphql/helloworld/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  # graphql mutation-idl
  - path: graphql/mutation-idl/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  # graphql relaytodo
  - path: graphql/relaytodo/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  # graphql mutation
  - path: graphql/mutation/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  # graphql starwars
  - path: graphql/starwars/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  # client standalone
  - path: client/standalone/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  # client tomcat
  - path: client/tomcat/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>

  # tram todolist
  - path: tram/light-tram-todolist/multi-module/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: tram/light-tram-todolist/multi-module/pom.xml
    match: <version.openapi-parser>\d*\.\d*\.\d*</version.openapi-parser>
  # tram todolist command
  - path: tram/light-tram-todolist/multi-module/tram-todo-command/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: tram/light-tram-todolist/multi-module/tram-todo-command/pom.xml
    match: <version.openapi-parser>\d*\.\d*\.\d*</version.openapi-parser>
  # tram todolist view
  - path: tram/light-tram-todolist/multi-module/tram-todo-view/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: tram/light-tram-todolist/multi-module/tram-todo-view/pom.xml
    match: <version.openapi-parser>\d*\.\d*\.\d*</version.openapi-parser>

  # saga customers orders
  - path: saga/light-saga-cutomers-and-orders/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: saga/light-saga-cutomers-and-orders/pom.xml
    match: <version.openapi-parser>\d*\.\d*\.\d*</version.openapi-parser>
  # saga customers orders order service
  - path: saga/light-saga-cutomers-and-orders/order-service/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: saga/light-saga-cutomers-and-orders/order-service/pom.xml
    match: <version.openapi-parser>\d*\.\d*\.\d*</version.openapi-parser>
  # saga customers orders customer service
  - path: saga/light-saga-cutomers-and-orders/customer-service/pom.xml
    match: <version.light[a-z-]+4j>\d*\.\d*\.\d*</version.light[a-z-]+4j>
  - path: saga/light-saga-cutomers-and-orders/customer-service/pom.xml
    match: <version.openapi-parser>\d*\.\d*\.\d*</version.openapi-parser>
